/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.app.proyecto.view;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author alber
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    public JButton getActualizar() {
        return Actualizar;
    }

    public void setActualizar(JButton Actualizar) {
        this.Actualizar = Actualizar;
    }

    public JRadioButton getAstringente() {
        return Astringente;
    }

    public void setAstringente(JRadioButton Astringente) {
        this.Astringente = Astringente;
    }

    public JRadioButton getAyuno() {
        return Ayuno;
    }

    public void setAyuno(JRadioButton Ayuno) {
        this.Ayuno = Ayuno;
    }

    public JRadioButton getBlanda() {
        return Blanda;
    }

    public void setBlanda(JRadioButton Blanda) {
        this.Blanda = Blanda;
    }

    public JButton getBorrar() {
        return Borrar;
    }

    public void setBorrar(JButton Borrar) {
        this.Borrar = Borrar;
    }

    public JButton getConsultar() {
        return Consultar;
    }

    public void setConsultar(JButton Consultar) {
        this.Consultar = Consultar;
    }

    public Integer getId() {
        try {
            return Integer.parseInt(Id.getText());
        } catch (Exception e) {
           Id.setText("0");
           return Integer.parseInt(Id.getText());
        }
        
    }

    public void setId(JTextField Id) {
        this.Id = Id;
    }

    public JButton getInsertar() {
        return Insertar;
    }

    public void setInsertar(JButton Insertar) {
        this.Insertar = Insertar;
    }

    public JRadioButton getSonda() {
        return Sonda;
    }

    public void setSonda(JRadioButton Sonda) {
        this.Sonda = Sonda;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dietas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Id = new javax.swing.JTextField();
        Texto_ID_Paciente = new javax.swing.JLabel();
        Insertar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Blanda = new javax.swing.JRadioButton();
        Astringente = new javax.swing.JRadioButton();
        Ayuno = new javax.swing.JRadioButton();
        Sonda = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Id.setText("0");
        Id.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                IdCaretUpdate(evt);
            }
        });
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });

        Texto_ID_Paciente.setText("ID Paciente");

        Insertar.setText("Insertar");

        Borrar.setText("Borrar");

        Actualizar.setText("Actualizar");

        Consultar.setText("Consultar");

        Dietas.add(Blanda);
        Blanda.setText("Dieta blanda");

        Dietas.add(Astringente);
        Astringente.setText("Dieta astringente");

        Dietas.add(Ayuno);
        Ayuno.setText("Dieta de ayuno");

        Dietas.add(Sonda);
        Sonda.setText("Dieta por sonda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Texto_ID_Paciente)
                                .addGap(30, 30, 30)
                                .addComponent(Id))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Insertar)
                                .addGap(18, 18, 18)
                                .addComponent(Borrar)))
                        .addGap(18, 18, 18)
                        .addComponent(Actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(Consultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blanda)
                            .addComponent(Astringente)
                            .addComponent(Ayuno)
                            .addComponent(Sonda))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto_ID_Paciente))
                .addGap(18, 18, 18)
                .addComponent(Blanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Astringente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ayuno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sonda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar)
                    .addComponent(Borrar)
                    .addComponent(Actualizar)
                    .addComponent(Consultar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        
    }//GEN-LAST:event_IdActionPerformed

    private void IdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_IdCaretUpdate
        
    }//GEN-LAST:event_IdCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JRadioButton Astringente;
    private javax.swing.JRadioButton Ayuno;
    private javax.swing.JRadioButton Blanda;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Consultar;
    private javax.swing.ButtonGroup Dietas;
    private javax.swing.JTextField Id;
    private javax.swing.JButton Insertar;
    private javax.swing.JRadioButton Sonda;
    private javax.swing.JLabel Texto_ID_Paciente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
